apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-network
  annotations:
    meta.crossplane.io/maintainer: Hops Platform Team <platform@hops.ops.com.ai>
    meta.crossplane.io/source: github.com/hops-ops/configuration-network
    meta.crossplane.io/description: |
      Network creates AWS VPCs with subnets, routing, NAT gateways, and optional
      enterprise features. Supports IPv4, IPv6, and dual-stack configurations.
spec:
  dependsOn:
  - provider: xpkg.crossplane.io/crossplane-contrib/provider-aws-ec2
    version: ">=v2.3.0"
  - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: ">=v0.6.0"