apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-network
spec:
  dependsOn:
  - provider: xpkg.upbound.io/crossplane-contrib/provider-aws-ec2
    version: ">=v2.2.0"
  - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
    version: ">=v0.5.1"
