name: on-push-main

on:
  push:
    branches:
    - main
    paths:
      - '.github/workflows/on-push-main.yaml'
      - '.github/workflows/on-version-tagged.yaml'
      - '.gitops/**'
      - 'apis/**'
      - 'examples/**'
      - 'functions/**'
      - 'tests/**'
      - 'upbound.yaml'

permissions:
  id-token: write
  packages: write
  contents: write
  issues: write
  pull-requests: write

jobs:

  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@feat/debug-logs
    with:
      examples: |
        [
          { "example": "examples/networks/minimal.yaml" },
          { "example": "examples/networks/standard.yaml" },
          { "example": "examples/networks/dual-stack-ula.yaml" },
          { "example": "examples/networks/dual-stack-amazon.yaml" },
          { "example": "examples/networks/high-availability.yaml" },
          { "example": "examples/networks/import-example.yaml" },
          { "example": "examples/networks/with-ipam.yaml", "observed_resources": "examples/test/mocks/observed-resources/with-ipam/steps/1" },
          { "example": "examples/networks/with-ipam.yaml", "observed_resources": "examples/test/mocks/observed-resources/with-ipam/steps/2" },
          { "example": "examples/networks/with-ipam.yaml", "observed_resources": "examples/test/mocks/observed-resources/with-ipam/steps/3" },
          { "example": "examples/networks/with-ipam.yaml", "observed_resources": "examples/test/mocks/observed-resources/with-ipam/steps/4" }
        ]
      api_path: apis/networks
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@feat/debug-logs

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e.yaml@feat/debug-logs
    with:
      aws: true
      aws-use-oidc: true
      aws-account-id: "034489662075"
      aws-region: us-east-2
      timeout-minutes: 30
      cleanup-timeout-minutes: 30

  version-and-tag:
    name: Version and Tag
    needs:
      - validate
      - test
      - e2e
    uses: unbounded-tech/workflow-vnext-tag/.github/workflows/workflow.yaml@v1.20.2
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    with:
      useDeployKey: true
      yqPatches: |
        patches:
          - filePath: .gitops/deploy/values.yaml
            selector: .version
            valuePrefix: "v"
          - filePath: .gitops/deploy/Chart.yaml
            selector: .version
            valuePrefix: ""

